spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: root
      # >= 8.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定 nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
        # NJ
        # 指定集群名称
#        cluster-name: BJ
#        metadata:
#          instance: c
#          haha: hehe
#          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          # 如果用的是RocketMQ,必须设置
          # 如果其他MQ,可留空
          group: binder-group
        my-input:
          destination: stream-my-topic
          group: my-group


  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center
#  zipkin:
#    base-url: http://localhost:9411/
#    discoveryClientEnabled: false
#  sleuth:
#    sampler:
#      # 抽样率，默认是0.1（10%）
#      probability: 1.0
server:
  port: 8081
#logging:
#  level:
#    com.alibaba.nacos: error
#    org.springframework.cloud.sleuth: debug
#jwt:
#  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
#  # 有效期，单位秒，默认2周
#  expire-time-in-second: 1209600
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always